CREATE TABLE events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(120) NOT NULL,
                        description TEXT NOT NULL,
                        location VARCHAR(255) NOT NULL,
                        capacity INTEGER NOT NULL,
                        status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
                        registration_deadline TIMESTAMP WITH TIME ZONE NOT NULL,
                        starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT ck_events_capacity
                            CHECK (capacity > 0),

                        CONSTRAINT ck_events_status
                            CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED')),

                        CONSTRAINT ck_events_registration_deadline
                            CHECK (registration_deadline <= starts_at),

                        CONSTRAINT ck_events_time_range
                            CHECK (ends_at > starts_at)
);