CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    email VARCHAR(254) NOT NULL ,
    password_hash VARCHAR(255) NOT NULL ,
    display_name VARCHAR(100) NOT NULL ,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_members_email
                     UNIQUE (email),
    CONSTRAINT ck_members_role
                     CHECK ( role IN ('MEMBER', 'ADMIN')),

    CONSTRAINT ck_members_mail_normailzed
                     CHECK ( email = LOWER(TRIM(email)) )
);