CREATE TABLE registrations (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               member_id BIGINT NOT NULL,
                               event_id BIGINT NOT NULL,
                               status VARCHAR(20) NOT NULL DEFAULT 'REGISTERED',
                               registered_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               cancelled_at TIMESTAMP WITH TIME ZONE,

                               CONSTRAINT fk_registrations_member
                                   FOREIGN KEY (member_id) REFERENCES members(id),

                               CONSTRAINT fk_registrations_event
                                   FOREIGN KEY (event_id) REFERENCES events(id),

                               CONSTRAINT uk_registrations_member_event
                                   UNIQUE (member_id, event_id),

                               CONSTRAINT ck_registrations_status
                                   CHECK (status IN ('REGISTERED', 'CANCELLED')),

                               CONSTRAINT ck_registrations_cancelled_at
                                   CHECK (
                                       (status = 'REGISTERED' AND cancelled_at IS NULL)
                                           OR
                                       (status = 'CANCELLED' AND cancelled_at IS NOT NULL)
                                       )
);

CREATE INDEX idx_registrations_event_status
    ON registrations (event_id, status);